overrides:
  next@>=16.0.0-beta.0 <16.2.3: '>=16.2.3'
  postcss@<8.5.10: '>=8.5.10'
  svix@<1.92.2: '>=1.92.2'
  uuid@<14.0.0: '>=14.0.0'

minimumReleaseAge: 1440

allowBuilds:
  '@nwpr/airport-codes': true
  '@sentry/cli': true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
