/**
 * B2B Invoice Business Logic
 * Core operations for managing B2B invoices
 */

import { createServiceRoleClient } from '@/lib/supabase';
import type { TablesUpdate } from '@/lib/types/database.generated';
import type {
  B2BInvoice,
  B2BInvoiceWithAttendees,
  B2BInvoiceAttendeeWithWorkshops,
  B2BInvoiceWorkshopItem,
  B2BInvoiceStatus,
  CreateB2BInvoiceRequest,
  UpdateB2BInvoiceRequest,
  WorkshopItemInput,
  ListInvoicesQuery,
} from '@/lib/types/b2b';
import { computeInvoiceTotals } from './invoice-calculations';

/**
 * Create a new B2B invoice
 *
 * @param data - Invoice creation data
 * @returns Created invoice with auto-generated invoice number
 * @throws Error if validation fails or database insert fails
 */
export async function createInvoice(data: CreateB2BInvoiceRequest): Promise<B2BInvoice> {
  const supabase = createServiceRoleClient();

  // Calculate totals (tickets + workshop seats)
  const vatRate = data.vatRate ?? 0;
  const { subtotal, vatAmount, totalAmount } = computeInvoiceTotals({
    unitPrice: data.unitPrice,
    ticketQuantity: data.ticketQuantity,
    workshopItems: data.workshopItems,
    vatRate,
  });

  const { data: invoice, error } = await supabase
    .from('b2b_invoices')
    .insert({
      // Invoice number is auto-generated by database trigger when empty
      invoice_number: '',

      // Company details
      company_name: data.companyName,
      vat_id: data.vatId || null,
      billing_address_street: data.billingAddress.street,
      billing_address_city: data.billingAddress.city,
      billing_address_postal_code: data.billingAddress.postalCode,
      billing_address_country: data.billingAddress.country,

      // Contact
      contact_name: data.contactName,
      contact_email: data.contactEmail,

      // Invoice settings
      due_date: data.dueDate,
      notes: data.notes || null,
      invoice_notes: data.invoiceNotes || null,
      payment_method: data.paymentMethod || 'bank_transfer',

      // Ticket configuration
      ticket_category: data.ticketCategory,
      ticket_stage: data.ticketStage,
      ticket_quantity: data.ticketQuantity,
      unit_price: data.unitPrice,
      currency: 'CHF',

      // Calculated totals
      subtotal,
      vat_rate: vatRate,
      vat_amount: vatAmount,
      total_amount: totalAmount,

      // Default status
      status: 'draft',
    })
    .select()
    .single();

  if (error) {
    console.error('Error creating invoice:', error);
    throw new Error(`Failed to create invoice: ${error.message}`);
  }

  // Insert workshop line items, rolling the invoice back on failure so we
  // never leave an invoice whose stored totals include missing lines.
  if (data.workshopItems && data.workshopItems.length > 0) {
    const { error: itemsError } = await supabase.from('b2b_invoice_workshop_items').insert(
      data.workshopItems.map((item) => ({
        invoice_id: invoice.id,
        workshop_id: item.workshopId,
        workshop_title: item.title,
        quantity: item.quantity,
        unit_price: item.unitPrice,
      }))
    );

    if (itemsError) {
      console.error('Error creating invoice workshop items:', itemsError);
      await supabase.from('b2b_invoices').delete().eq('id', invoice.id);
      throw new Error(`Failed to create invoice workshop items: ${itemsError.message}`);
    }
  }

  return invoice as B2BInvoice;
}

/**
 * Get all workshop line items for an invoice
 */
export async function getWorkshopItems(invoiceId: string): Promise<B2BInvoiceWorkshopItem[]> {
  const supabase = createServiceRoleClient();

  const { data, error } = await supabase
    .from('b2b_invoice_workshop_items')
    .select('*')
    .eq('invoice_id', invoiceId)
    .order('created_at', { ascending: true });

  if (error) {
    throw new Error(`Failed to fetch invoice workshop items: ${error.message}`);
  }

  return (data || []) as B2BInvoiceWorkshopItem[];
}

/**
 * Get a single invoice by ID
 *
 * @param invoiceId - UUID of the invoice
 * @returns Invoice or null if not found
 */
export async function getInvoice(invoiceId: string): Promise<B2BInvoice | null> {
  const supabase = createServiceRoleClient();

  const { data, error } = await supabase
    .from('b2b_invoices')
    .select('*')
    .eq('id', invoiceId)
    .single();

  if (error) {
    if (error.code === 'PGRST116') {
      return null; // Not found
    }
    console.error('Error fetching invoice:', error);
    throw new Error(`Failed to fetch invoice: ${error.message}`);
  }

  return data as B2BInvoice;
}

/**
 * Get invoice with all attendees
 *
 * @param invoiceId - UUID of the invoice
 * @returns Invoice with attendees or null if not found
 */
export async function getInvoiceWithAttendees(
  invoiceId: string
): Promise<B2BInvoiceWithAttendees | null> {
  const supabase = createServiceRoleClient();

  // Fetch invoice
  const { data: invoice, error: invoiceError } = await supabase
    .from('b2b_invoices')
    .select('*')
    .eq('id', invoiceId)
    .single();

  if (invoiceError) {
    if (invoiceError.code === 'PGRST116') {
      return null;
    }
    throw new Error(`Failed to fetch invoice: ${invoiceError.message}`);
  }

  // Fetch attendees
  const { data: attendees, error: attendeesError } = await supabase
    .from('b2b_invoice_attendees')
    .select('*')
    .eq('invoice_id', invoiceId)
    .order('created_at', { ascending: true });

  if (attendeesError) {
    throw new Error(`Failed to fetch attendees: ${attendeesError.message}`);
  }

  // Fetch workshop line items + seat assignments
  const workshopItems = await getWorkshopItems(invoiceId);

  const itemIdsByAttendee = new Map<string, string[]>();
  if (workshopItems.length > 0) {
    const { data: assignments, error: assignmentsError } = await supabase
      .from('b2b_invoice_attendee_workshops')
      .select('attendee_id, workshop_item_id')
      .in(
        'workshop_item_id',
        workshopItems.map((item) => item.id)
      );

    if (assignmentsError) {
      throw new Error(`Failed to fetch workshop assignments: ${assignmentsError.message}`);
    }

    for (const assignment of assignments || []) {
      const list = itemIdsByAttendee.get(assignment.attendee_id) ?? [];
      list.push(assignment.workshop_item_id);
      itemIdsByAttendee.set(assignment.attendee_id, list);
    }
  }

  const attendeesWithWorkshops: B2BInvoiceAttendeeWithWorkshops[] = (attendees || []).map(
    (attendee) => ({
      ...attendee,
      workshop_item_ids: itemIdsByAttendee.get(attendee.id) ?? [],
    })
  ) as B2BInvoiceAttendeeWithWorkshops[];

  return {
    ...invoice,
    attendees: attendeesWithWorkshops,
    workshop_items: workshopItems,
  } as B2BInvoiceWithAttendees;
}

/**
 * List invoices with optional filtering and pagination
 *
 * @param query - Query parameters for filtering
 * @returns List of invoices and total count
 */
export async function listInvoices(query: ListInvoicesQuery = {}): Promise<{
  invoices: B2BInvoice[];
  total: number;
}> {
  const supabase = createServiceRoleClient();
  const { status, search, page = 1, limit = 20 } = query;

  let queryBuilder = supabase.from('b2b_invoices').select('*', { count: 'exact' });

  // Filter by status
  if (status) {
    queryBuilder = queryBuilder.eq('status', status);
  }

  // Search by company name or invoice number
  if (search) {
    queryBuilder = queryBuilder.or(
      `company_name.ilike.%${search}%,invoice_number.ilike.%${search}%`
    );
  }

  // Pagination
  const offset = (page - 1) * limit;
  queryBuilder = queryBuilder
    .order('created_at', { ascending: false })
    .range(offset, offset + limit - 1);

  const { data, error, count } = await queryBuilder;

  if (error) {
    console.error('Error listing invoices:', error);
    throw new Error(`Failed to list invoices: ${error.message}`);
  }

  return {
    invoices: (data || []) as B2BInvoice[],
    total: count || 0,
  };
}

/**
 * Update an existing invoice
 * Only allowed for invoices in draft or sent status
 *
 * @param invoiceId - UUID of the invoice
 * @param data - Fields to update
 * @returns Updated invoice
 * @throws Error if invoice is in paid/cancelled status
 */
export async function updateInvoice(
  invoiceId: string,
  data: UpdateB2BInvoiceRequest
): Promise<B2BInvoice> {
  const supabase = createServiceRoleClient();

  // First, check current status
  const existing = await getInvoice(invoiceId);
  if (!existing) {
    throw new Error('Invoice not found');
  }

  if (existing.status === 'paid' || existing.status === 'cancelled') {
    throw new Error(`Cannot update invoice with status: ${existing.status}`);
  }

  // Build update object
  const updateData: TablesUpdate<'b2b_invoices'> = {};

  if (data.companyName !== undefined) updateData.company_name = data.companyName;
  if (data.vatId !== undefined) updateData.vat_id = data.vatId || null;
  if (data.contactName !== undefined) updateData.contact_name = data.contactName;
  if (data.contactEmail !== undefined) updateData.contact_email = data.contactEmail;
  if (data.dueDate !== undefined) updateData.due_date = data.dueDate;
  if (data.notes !== undefined) updateData.notes = data.notes || null;
  if (data.invoiceNotes !== undefined) updateData.invoice_notes = data.invoiceNotes || null;
  if (data.paymentMethod !== undefined) updateData.payment_method = data.paymentMethod;
  if (data.ticketCategory !== undefined) updateData.ticket_category = data.ticketCategory;
  if (data.ticketStage !== undefined) updateData.ticket_stage = data.ticketStage;

  // Handle billing address partial updates
  if (data.billingAddress) {
    if (data.billingAddress.street !== undefined) {
      updateData.billing_address_street = data.billingAddress.street;
    }
    if (data.billingAddress.city !== undefined) {
      updateData.billing_address_city = data.billingAddress.city;
    }
    if (data.billingAddress.postalCode !== undefined) {
      updateData.billing_address_postal_code = data.billingAddress.postalCode;
    }
    if (data.billingAddress.country !== undefined) {
      updateData.billing_address_country = data.billingAddress.country;
    }
  }

  // Replace workshop line items when provided (full replacement). Deleting
  // the old items cascades to any attendee seat assignments on them.
  if (data.workshopItems !== undefined) {
    await replaceWorkshopItems(invoiceId, data.workshopItems);
  }

  // Recalculate totals if any pricing input changed
  const unitPrice = data.unitPrice ?? existing.unit_price;
  const ticketQuantity = data.ticketQuantity ?? existing.ticket_quantity;
  const vatRate = data.vatRate ?? existing.vat_rate;

  if (
    data.unitPrice !== undefined ||
    data.ticketQuantity !== undefined ||
    data.vatRate !== undefined ||
    data.workshopItems !== undefined
  ) {
    updateData.unit_price = unitPrice;
    updateData.ticket_quantity = ticketQuantity;
    updateData.vat_rate = vatRate;

    const workshopLines =
      data.workshopItems ??
      (await getWorkshopItems(invoiceId)).map((item) => ({
        quantity: item.quantity,
        unitPrice: item.unit_price,
      }));

    const totals = computeInvoiceTotals({
      unitPrice,
      ticketQuantity,
      workshopItems: workshopLines,
      vatRate,
    });

    updateData.subtotal = totals.subtotal;
    updateData.vat_amount = totals.vatAmount;
    updateData.total_amount = totals.totalAmount;
  }

  const { data: updated, error } = await supabase
    .from('b2b_invoices')
    .update(updateData)
    .eq('id', invoiceId)
    .select()
    .single();

  if (error) {
    console.error('Error updating invoice:', error);
    throw new Error(`Failed to update invoice: ${error.message}`);
  }

  return updated as B2BInvoice;
}

/**
 * Replace the workshop line items on an invoice
 * Lines for workshops that stay on the invoice are updated in place so their
 * attendee seat assignments survive; removed lines cascade-delete theirs.
 */
async function replaceWorkshopItems(
  invoiceId: string,
  items: WorkshopItemInput[]
): Promise<void> {
  const supabase = createServiceRoleClient();

  const existing = await getWorkshopItems(invoiceId);
  const existingByWorkshopId = new Map(existing.map((item) => [item.workshop_id, item]));
  const nextWorkshopIds = new Set(items.map((item) => item.workshopId));

  // Remove lines whose workshop is no longer on the invoice
  const removedIds = existing
    .filter((item) => !nextWorkshopIds.has(item.workshop_id))
    .map((item) => item.id);

  if (removedIds.length > 0) {
    const { error: deleteError } = await supabase
      .from('b2b_invoice_workshop_items')
      .delete()
      .in('id', removedIds);

    if (deleteError) {
      throw new Error(`Failed to update invoice workshop items: ${deleteError.message}`);
    }
  }

  for (const item of items) {
    const current = existingByWorkshopId.get(item.workshopId);

    if (!current) {
      const { error: insertError } = await supabase.from('b2b_invoice_workshop_items').insert({
        invoice_id: invoiceId,
        workshop_id: item.workshopId,
        workshop_title: item.title,
        quantity: item.quantity,
        unit_price: item.unitPrice,
      });

      if (insertError) {
        throw new Error(`Failed to update invoice workshop items: ${insertError.message}`);
      }
      continue;
    }

    if (
      current.quantity === item.quantity &&
      current.unit_price === item.unitPrice &&
      current.workshop_title === item.title
    ) {
      continue;
    }

    // Don't let the seat count drop below what's already assigned to attendees
    if (item.quantity < current.quantity) {
      const { count: assignedCount, error: countError } = await supabase
        .from('b2b_invoice_attendee_workshops')
        .select('*', { count: 'exact', head: true })
        .eq('workshop_item_id', current.id);

      if (countError) {
        throw new Error(`Failed to update invoice workshop items: ${countError.message}`);
      }

      if ((assignedCount || 0) > item.quantity) {
        throw new Error(
          `Cannot reduce "${current.workshop_title}" to ${item.quantity} seat(s): ` +
            `${assignedCount} attendee(s) are already assigned. Unassign attendees first.`
        );
      }
    }

    const { error: updateError } = await supabase
      .from('b2b_invoice_workshop_items')
      .update({
        workshop_title: item.title,
        quantity: item.quantity,
        unit_price: item.unitPrice,
      })
      .eq('id', current.id);

    if (updateError) {
      throw new Error(`Failed to update invoice workshop items: ${updateError.message}`);
    }
  }
}

/**
 * Update invoice status
 * Validates that the transition is allowed
 *
 * @param invoiceId - UUID of the invoice
 * @param newStatus - New status to set
 * @throws Error if transition is invalid
 */
export async function updateInvoiceStatus(
  invoiceId: string,
  newStatus: B2BInvoiceStatus
): Promise<B2BInvoice> {
  const supabase = createServiceRoleClient();

  // Get current invoice
  const existing = await getInvoice(invoiceId);
  if (!existing) {
    throw new Error('Invoice not found');
  }

  // Import and use the validation function
  const { isValidStatusTransition } = await import('@/lib/types/b2b');

  // Validate transition
  if (!isValidStatusTransition(existing.status, newStatus)) {
    throw new Error(
      `Invalid status transition: ${existing.status} -> ${newStatus}. ` +
        `Allowed transitions from ${existing.status}: ${
          existing.status === 'draft'
            ? 'sent, cancelled'
            : existing.status === 'sent'
              ? 'paid, cancelled'
              : 'none'
        }`
    );
  }

  const { data: updated, error } = await supabase
    .from('b2b_invoices')
    .update({ status: newStatus })
    .eq('id', invoiceId)
    .select()
    .single();

  if (error) {
    console.error('Error updating invoice status:', error);
    throw new Error(`Failed to update invoice status: ${error.message}`);
  }

  return updated as B2BInvoice;
}

/**
 * Delete an invoice
 * Only allowed for invoices in draft status
 *
 * @param invoiceId - UUID of the invoice
 * @throws Error if invoice is not in draft status
 */
export async function deleteInvoice(invoiceId: string): Promise<void> {
  const supabase = createServiceRoleClient();

  // Check current status
  const existing = await getInvoice(invoiceId);
  if (!existing) {
    throw new Error('Invoice not found');
  }

  if (existing.status !== 'draft') {
    throw new Error(`Cannot delete invoice with status: ${existing.status}. Only draft invoices can be deleted.`);
  }

  const { error } = await supabase.from('b2b_invoices').delete().eq('id', invoiceId);

  if (error) {
    console.error('Error deleting invoice:', error);
    throw new Error(`Failed to delete invoice: ${error.message}`);
  }
}

/**
 * Update invoice PDF details
 *
 * @param invoiceId - UUID of the invoice
 * @param pdfUrl - URL to the PDF file
 * @param source - Whether PDF was generated or uploaded
 */
export async function updateInvoicePDF(
  invoiceId: string,
  pdfUrl: string,
  source: 'generated' | 'uploaded'
): Promise<B2BInvoice> {
  const supabase = createServiceRoleClient();

  const { data: updated, error } = await supabase
    .from('b2b_invoices')
    .update({
      invoice_pdf_url: pdfUrl,
      invoice_pdf_source: source,
      invoice_pdf_uploaded_at: new Date().toISOString(),
    })
    .eq('id', invoiceId)
    .select()
    .single();

  if (error) {
    console.error('Error updating invoice PDF:', error);
    throw new Error(`Failed to update invoice PDF: ${error.message}`);
  }

  return updated as B2BInvoice;
}

/**
 * Update invoice Stripe payment link
 *
 * @param invoiceId - UUID of the invoice
 * @param paymentLinkId - Stripe Payment Link ID
 * @param paymentLinkUrl - Stripe Payment Link URL
 */
export async function updateStripePaymentLink(
  invoiceId: string,
  paymentLinkId: string,
  paymentLinkUrl: string
): Promise<B2BInvoice> {
  const supabase = createServiceRoleClient();

  const { data: updated, error } = await supabase
    .from('b2b_invoices')
    .update({
      stripe_payment_link_id: paymentLinkId,
      stripe_payment_link_url: paymentLinkUrl,
    })
    .eq('id', invoiceId)
    .select()
    .single();

  if (error) {
    console.error('Error updating Stripe payment link:', error);
    throw new Error(`Failed to update Stripe payment link: ${error.message}`);
  }

  return updated as B2BInvoice;
}

/**
 * Remove invoice PDF
 *
 * @param invoiceId - UUID of the invoice
 */
export async function removeInvoicePDF(invoiceId: string): Promise<B2BInvoice> {
  const supabase = createServiceRoleClient();

  const { data: updated, error } = await supabase
    .from('b2b_invoices')
    .update({
      invoice_pdf_url: null,
      invoice_pdf_source: null,
      invoice_pdf_uploaded_at: null,
    })
    .eq('id', invoiceId)
    .select()
    .single();

  if (error) {
    console.error('Error removing invoice PDF:', error);
    throw new Error(`Failed to remove invoice PDF: ${error.message}`);
  }

  return updated as B2BInvoice;
}
