/**
 * Shared Submission View for Reviewers
 * Accessed via a secure share link generated by an admin.
 * Shows the full de-anonymized submission (speaker identity, resources, reviews).
 * Read-only — no review form is shown.
 */

import React from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/router';
import type { GetServerSideProps } from 'next';
import { ChevronLeft, ChevronRight, Info, Link2 } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { SEO } from '@/components/SEO';
import { Heading } from '@/components/atoms';
import { createSupabaseServerClient } from '@/lib/cfp/auth';
import { reviewerSharedSubmissionQueryOptions } from '@/lib/queries/cfp';
import {
  ReviewerPill,
  TYPE_LABELS,
  SpeakerInfo,
  CommitteeReviews,
  SubmissionDetails,
} from '@/components/cfp/reviewer';

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const supabaseServer = createSupabaseServerClient(ctx);
  const { data: { session } } = await supabaseServer.auth.getSession();

  if (!session) {
    const returnTo = ctx.resolvedUrl;
    return {
      redirect: {
        destination: `/cfp/reviewer/login?returnTo=${encodeURIComponent(returnTo)}`,
        permanent: false,
      },
    };
  }

  return { props: {} };
};

export default function SharedSubmissionPage() {
  const router = useRouter();
  const { token } = router.query;
  const tokenStr = typeof token === 'string' ? token : '';

  // Fetch shared submission data
  const { data, isLoading, error } = useQuery(
    reviewerSharedSubmissionQueryOptions(tokenStr)
  );

  const submission = data?.submission ?? null;
  const reviewer = data?.reviewer ?? null;
  const shareNote = data?.share?.note ?? null;

  // Loading state
  if (isLoading) {
    return (
      <div className="min-h-screen bg-brand-gray-darkest flex items-center justify-center">
        <div className="text-center">
          <div className="w-12 h-12 border-4 border-brand-primary border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <p className="text-brand-gray-light">Loading shared submission...</p>
        </div>
      </div>
    );
  }

  if (error || !submission || !reviewer) {
    return (
      <div className="min-h-screen bg-brand-gray-darkest flex items-center justify-center">
        <div className="text-center max-w-md mx-auto px-4">
          <p className="text-red-400 mb-4">
            {error instanceof Error ? error.message : 'This share link is invalid or has expired.'}
          </p>
          <Link
            href="/cfp/reviewer/dashboard"
            className="px-4 py-2 bg-brand-primary text-black rounded-lg font-medium inline-block"
          >
            Back to Dashboard
          </Link>
        </div>
      </div>
    );
  }

  return (
    <>
      <SEO
        title={`Shared: ${submission.title} | CFP`}
        description="View shared CFP submission"
        noindex
      />

      <div className="min-h-screen bg-brand-gray-darkest overflow-x-hidden">
        {/* Header */}
        <header className="border-b border-brand-gray-dark">
          <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
            <Link href="/cfp/reviewer/dashboard" className="flex items-center gap-3">
              <Image
                src="/images/logo/zurichjs-square.png"
                alt="ZurichJS"
                width={40}
                height={40}
              />
              <span className="text-white font-semibold">Zurich JS Conf 2026</span>
            </Link>
            <div className="flex items-center gap-4">
              <Link
                href="/cfp/reviewer/dashboard"
                className="text-brand-gray-light hover:text-white text-sm transition-colors inline-flex items-center gap-2"
              >
                <ChevronLeft className="w-4 h-4" />
                Back<span className="hidden sm:inline"> to Dashboard</span>
              </Link>
            </div>
          </div>
        </header>

        <main className="max-w-5xl mx-auto px-4 py-8">
          {/* Breadcrumb Navigation */}
          <nav className="flex items-center gap-2 text-sm mb-6">
            <Link
              href="/cfp/reviewer/dashboard"
              className="text-white font-semibold hover:text-brand-primary transition-colors"
            >
              Dashboard
            </Link>
            <ChevronRight className="w-4 h-4 text-brand-gray-medium" />
            <span className="text-brand-gray-light flex items-center gap-1.5">
              <Link2 className="w-3.5 h-3.5" />
              Shared Submission
            </span>
            <ChevronRight className="w-4 h-4 text-brand-gray-medium" />
            <span className="text-brand-gray-light truncate max-w-[200px] sm:max-w-[300px]">
              {submission.title}
            </span>
          </nav>

          {/* Share Context Banner */}
          <div className="bg-brand-primary/10 border border-brand-primary/30 rounded-xl p-4 mb-6">
            <div className="flex items-start gap-3">
              <Info className="w-5 h-5 text-brand-primary flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-medium text-brand-primary">
                  Shared for Review
                </p>
                <p className="text-xs text-brand-gray-light mt-1">
                  An admin shared this submission with you for review. Speaker identity and full details are visible below.
                </p>
                {shareNote && (
                  <p className="text-sm text-white mt-2 bg-brand-gray-dark rounded-lg px-3 py-2">
                    &ldquo;{shareNote}&rdquo;
                  </p>
                )}
              </div>
            </div>
          </div>

          <div className="space-y-6">
            {/* Header */}
            <div>
              <div className="flex items-center gap-2 mb-2">
                <ReviewerPill tone="yellow">
                  {TYPE_LABELS[submission.submission_type]}
                </ReviewerPill>
                <ReviewerPill tone="purple" className="capitalize">
                  {submission.talk_level}
                </ReviewerPill>
              </div>
              <Heading level="h1" className="text-xl sm:text-2xl font-bold text-white mb-4">
                {submission.title}
              </Heading>
            </div>

            {/* Speaker Info — always shown since the share link grants full access */}
            {submission.speaker && (
              <SpeakerInfo speaker={submission.speaker} />
            )}

            {/* Submission Content — full admin-like view */}
            <SubmissionDetails
              submission={submission}
              isAnonymous={false}
              isSuperAdmin={true}
            />

            {/* Committee Reviews */}
            {submission.all_reviews && submission.all_reviews.length > 0 && (
              <CommitteeReviews
                reviews={submission.all_reviews}
                stats={submission.stats}
              />
            )}
          </div>
        </main>
      </div>
    </>
  );
}
